# ${doNotModifyComment}
image:
  repository: ${IMAGE_REPOSITORY}
  pullPolicy: IfNotPresent
  tag: "${IMAGE_TAG}"
ssh:
  authorized_keys: |-
    ${HOME_PUBLIC_KEY}
service:
  type: ClusterIP
  port: 22
  nodePort:
    port: 30022