apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "base-develop-environtment.fullname" . }}
  labels:
    {{- include "base-develop-environtment.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "base-develop-environtment.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "base-develop-environtment.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "base-develop-environtment.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: base-develop-environtment-config-volume
          configMap:
            name: {{ include "base-develop-environtment.configmap.name" . }}
            defaultMode: 0600
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /root/.ssh/authorized_keys
              name: base-develop-environtment-config-volume
              subPath: authorized_keys
              readOnly: true
          livenessProbe:
            exec:
              command:
                - "bash"
                - "-c"
                - "systemctl is-active sshd && systemctl is-active docker"
            failureThreshold: 20
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - "bash"
                - "-c"
                - "systemctl is-active sshd && systemctl is-active docker"
            failureThreshold: 20
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
